---
title: "DNA Analysis"
output:
  html_document:
    df_print: paged
    toc: true
editor_options: 
  chunk_output_type: console
vignette: >
  %\VignetteIndexEntry{DNA Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r include=FALSE}

library(TapestriR)
library(rhdf5)
library(tidyverse)
library(ggplot2)
library(plotly)
library(patchwork)

# umap library
library(uwot)

# protein normalization library
library(SciViews)

# louvain clustering
library(scran)

ASSAY_NAME_VARIANT = 'dna'
ASSAY_NAME_READ_COUNT = 'cnv'
ASSAY_NAME_PROTEIN = 'protein'



```

### Load data

to do:
* meta data summary? 
* filter options identical to insights
* annotate variant and amplicons so I can easily select

```{r load data, cache=TRUE}

filename <- system.file("extdata", "PE11.cells.loom", package = "TapestriR")

variants = read_loom(filename,min_mutation_rate = 0.1)

filtered_variants = filter_variants(variants)
vaf=round(filtered_variants@data_layers$AD/filtered_variants@data_layers$DP, 3)
vaf[is.na(vaf)] <- 0
filtered_variants = add_data_layer(filtered_variants,'VAF',vaf)

```

### Cluster SNV

clustering by kmeans and louvain on umap projection and raw features

```{r cluster_snv}

##################
# do demension reduction and clustering a few different ways
##################

#dimensional reduction using umap
set.seed(111)
umap_values <- umap(filtered_variants$data_layers$VAF, scale=TRUE, metric="manhattan", init="laplacian", pca=20) 

umap_layer = tibble(    
      x = umap_values[,1],
      y = umap_values[,2]
)

filtered_variants = add_analysis_layer(assay = filtered_variants, layer_name = 'umap_vaf',data = umap_layer)
  
######
# Hold all the different customer labels in a single structure
#####
cluster_by = filtered_variants@analysis_layers$umap_vaf
clusters = list()

#### do the clustering

for(i in 2:5) {
  kmean_values <- kmeans(cluster_by, i ,iter.max=500)
  clusters[[paste0('umap.kmean.cluster.',i)]] = as_factor(kmean_values$cluster)

  kmean_values <- kmeans(cluster_by, i ,iter.max=500)
  clusters[[paste0('feature.kmean.cluster.',i)]] = as_factor(kmean_values$cluster)

}

graph_values <- buildSNNGraph(t(cluster_by), k=150)
louvain_clust <- igraph::cluster_louvain(graph_values)$membership

clusters[['umap.louvain.cluster']] = as_factor(louvain_clust)

graph_values <- buildSNNGraph(t(cluster_by), k=150)
louvain_clust <- igraph::cluster_louvain(graph_values)$membership

clusters[['features.louvain.cluster']] = as_factor(louvain_clust)



#############
## Add cluster labels to analysis data structure
#############
filtered_variants = add_analysis_layer( assay = filtered_variants,
                                           layer_name  = 'umap_vaf_clusters',
                                           data = as_tibble(clusters))


```

#### plot UMAP and Clusters

plot all the different clusters on the same umap projection

```{r fig.width = 12, fig.height = 8}

p  = tapestri_scatterplot(
                 x = filtered_variants@analysis_layers$umap_vaf$x, 
                 y= filtered_variants@analysis_layers$umap_vaf$y, 
                 color_by = filtered_variants@analysis_layers$umap_vaf_clusters$umap.kmean.cluster.2)
p = p + umap_theme() + ggtitle('umap_vaf_clusters')



q  = tapestri_scatterplot(
                 x = filtered_variants@analysis_layers$umap_vaf$x, 
                 y= filtered_variants@analysis_layers$umap_vaf$y, 
                 color_by = filtered_variants@data_layers$AD)
q = q + umap_theme() + ggtitle('umap_vaf_clusters')

p + q

```
